### ISSUE TITLE
Establish Initial ETL Pipeline

### ISSUE THREAD

**Issue by bellanov** [bellanov/etl-pipeline#1]
Port the current implementation of the **ETL Pipeline** from **Andy** to this project.

**Comment by aybanda** [comment]
@bellanov 
#2  check this if you have not already.
imported ETL pipeline successfully from andy

**Comment by bellanov** [comment]
Awesome 👌

**Comment by bellanov** [comment]
I can install things locally but will need to update the tests to reference the installed package.

![Image](https://github.com/user-attachments/assets/d443e465-b993-487f-894e-dfd444d9d85e)

**Comment by bellanov** [comment]
This specifically. You can even interact with things within the Python interperter.

![Image](https://github.com/user-attachments/assets/4f589b26-4d28-4dd1-b5a9-c7b16ad0a219)

**Comment by bellanov** [comment]
Going to add one config step, so a **pipeline.config({})** at some point that accepts a configuration, them simply executes the pipeline.

This may help clean things up by doing away with environment variables, but that's a later thing.
