### ISSUE TITLE
Officially Open Source / Publish to PyPi

### ISSUE THREAD

**Issue by bellanov** [bellanov/etl-pipeline#4]
I'm currently working on officially publishing this to pypi and the workflow that entails. Once that's done, we'll officially be a new piece of Open Source. 

From there onward, we simply iterate, tag, version, and repeat.

Tasks:

- Come up with a unique name for this, just in case.

**Comment by aybanda** [comment]
you can consider something like 'HarmonicETL' for balanced approach to data workflows
or 'SerenadeFlow or SerenadeETL' for smooth data processing experience.
I would prefer SerenadeFlow it is more pleasing and unique.

**Comment by bellanov** [comment]
Very nice!!!

**Comment by bellanov** [comment]
Cool, now we have the paper trail. At some point, users will request features in the form of issues on the project.

**Comment by bellanov** [comment]
Almost done tying things together, then just have to officially rename it.

![Image](https://github.com/user-attachments/assets/ab3a5c51-47ad-4f3e-9cec-a7bc623445c9)

**Comment by bellanov** [comment]
Current state is now up on **testpypi**. I just need to finish consuming your other changes then we start iterating here. Things like linting and some additional documentation are to come.

**Reference:**

https://test.pypi.org/project/andy-serenade-flow/

**Comment by bellanov** [comment]
Take note of the difference when installing a package from testpypi versus the production one.

![Image](https://github.com/user-attachments/assets/51ad4171-d7d3-422f-a56d-22641057a8be)

**Comment by bellanov** [comment]
Interacting with the project in terms of it being a package is a lot more powerful. Users could just import the pieces they like, not necessarily tie themselves to our implementation.

**Comment by bellanov** [comment]
How things look with the package being installed locally. 

![Image](https://github.com/user-attachments/assets/e00ca713-07d0-4c4d-ab80-06a3dd4db8b9)

**Comment by aybanda** [comment]
Great going
Seems smooth, so far @bellanov

**Comment by bellanov** [comment]
Indeed. Once things are set, we can focus on just cranking out features.
